#!/usr/bin/env python3
"""
Создаёт папку analytics/ на GitHub с начальными файлами.
Запусти один раз: python3 create_analytics_folder.py
"""
import json, os, base64, urllib.request, ssl
from datetime import datetime, timezone, timedelta

BASE   = os.path.dirname(os.path.abspath(__file__))
CONFIG = os.path.join(BASE, "config.json")

with open(CONFIG) as f:
    cfg = json.load(f)

GH_TOKEN = cfg["github_token"]
GH_REPO  = cfg.get("github_repo", "ivanmartynov97/telegram-posts")

def ssl_ctx():
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx

def gh_put(path, obj, msg):
    url  = f"https://api.github.com/repos/{GH_REPO}/contents/{path}"
    body = json.dumps({
        "message": msg,
        "content": base64.b64encode(
            json.dumps(obj, ensure_ascii=False, indent=2).encode()
        ).decode()
    }).encode()
    req = urllib.request.Request(url, data=body, method="PUT",
        headers={"Authorization": f"token {GH_TOKEN}",
                 "Accept": "application/vnd.github.v3+json",
                 "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15, context=ssl_ctx()) as r:
        return json.loads(r.read())

def gh_get(path):
    url = f"https://api.github.com/repos/{GH_REPO}/contents/{path}"
    req = urllib.request.Request(url,
        headers={"Authorization": f"token {GH_TOKEN}",
                 "Accept": "application/vnd.github.v3+json"})
    try:
        with urllib.request.urlopen(req, timeout=10, context=ssl_ctx()) as r:
            return json.loads(r.read())
    except:
        return None

# 1. Проверяем subscriber_history.json
print("Проверяю analytics/subscriber_history.json...")
existing = gh_get("analytics/subscriber_history.json")
if existing:
    print("  ✅ Уже существует")
else:
    now = datetime.now(timezone(timedelta(hours=3)))
    history = [{"date": now.strftime("%Y-%m-%d"), "count": None, "note": "initial"}]
    gh_put("analytics/subscriber_history.json", history, "Init: subscriber_history.json")
    print("  ✅ Создан analytics/subscriber_history.json")

# 2. Проверяем analytics/.gitkeep (чтобы папка видна)
print("Проверяю analytics/README...")
existing2 = gh_get("analytics/README.md")
if not existing2:
    gh_put("analytics/README.md",
        {"info": "Analytics data. Auto-generated by auto_publish.py and early_performance.py"},
        "Init analytics folder")
    print("  ✅ Создан analytics/README.md")
else:
    print("  ✅ Уже существует")

print("\n✅ Готово! Папка analytics/ создана на GitHub.")
print("   Данные появятся автоматически после первой публикации поста через auto_publish.py")
